#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>


// checks if the input path is a file(return 1), directory(return 0), or exists(return -1)//
//
int isFile(const char* path){
	struct stat path_stat;
	printf("%s path in isFile function\n", path);
	stat(path, &path_stat);
	if(S_ISREG(path_stat.st_mode))
	{
		return 1;
	}
	else if(S_ISDIR(path_stat.st_mode))
	{
		return 0;	 
	}
	else
	{
		return -1;
	}
}

//calls ls -1 on inputted path and stores that in some text file // 
//
void file_searcher(const char* initpath)
{
		char buff[512];
		sprintf(buff, "touch %stemppaths.txt && ls -1 %s >> %stemppaths.txt", initpath, initpath, initpath);
		system(buff);
}	
/*(attemps) to read text file generated by file_searcher and parse the line determined by lineindex into an array, although i cant get it to 
 store the output properly in char* line so it can be returned*/ 
//
char* parse_paths(char* line, const char* path, int lineindex)
{
	FILE *pFile;
	char buff[512];
	char buff2[512];
	printf("%d", lineindex);
	printf("%s path in parsepaths \n", path);
	sprintf(buff, "%stemppaths.txt", path);
	printf("%s tempfile name\n", buff);
	pFile = fopen(buff, "r");
	if (pFile==NULL) 
	{
		perror("error opening file");
		printf("error");
	}
	else
	{
		int i;
		int k;
		for(i = 0; i < lineindex; i = i+1){
			char buff3[512];
			if(fgets(buff3, 512, pFile) == NULL)
			{
				printf("break was called \n");
				break;
			}
			else
			{
				int j;
				for(j = 0; j < 512; j = j+1)
				{
					if(buff3[j] == '\n') 
					{
						k = j+1;
						break;
					}
					
					else
					{
						buff2[j] = buff3[j];
					}
				
				}
				buff2[k] = '\0';
				printf("%s line in buffer\n", buff2);
			}
		}
		strcpy(line, buff2);
			
	}

	fclose(pFile);
	printf("%s parse_paths line \n",line);
	return line;
}

//counts # lines in file 
//
int file_line_count(const char* path)
{
	FILE *fp;
	int count = 0;
	char c;
	char buff[512];
	sprintf(buff, "%stemppaths.txt", path);
	fp = fopen(buff, "r");

	if (fp == NULL)
	{
		return 0;
	}

	for (c = fgetc(fp); c!=EOF; c = fgetc(fp))
	{
		if(c == '\n')
		{
			//printf("%d", count);
			count = count +1;
		}
	}
	fclose(fp);
	//printf("%d", count);
	return count;


}

//inserts a file object into .json file//
//
void json_finserter(const char line[])
{
	char buff[512];
	sprintf(buff, "echo \"{\\\"path\\\":\\\"%s\\\", \\\"isdir\\\":0, \\\"objnum\\\":0, \\\"subdir\\\":[]}\" >> filesystem.json", line);
	system(buff);
}
//inserts a dir object into .json file (including all elements of that directory in the subdir array), not currently working, due to parse_paths
//
void json_dinserter(const char* path, const char* tmp_file)
{
	char buff[512];
	char file_paths[512];
	char cat[512];
	sprintf(cat, "cat %stemppaths.txt", path);
	sprintf(file_paths, "rm %stemppaths.txt", path);
	file_searcher(path);
	system(cat);
	int objnum = file_line_count(path);
	char lines[objnum][512];
	printf("%lu\n", sizeof(lines[0]));
	char directories[objnum][512];
	sprintf(buff, "echo \"{\\\"path\\\":\\\"%s\\\", \\\"isdir\\\":1, \\\"objnum\\\":%d, \\\"subdir\\\":[\" >> filesystem.json", path, objnum);
	system(buff);
	printf("%d\n", objnum);
	int i;
	int n = 0;

	for(i = 0; i < objnum; i = i+1)
	{
		char objpath[512];
		printf("%lu\n", sizeof(lines[i]));
		strcpy(lines[i] , parse_paths(lines[i], path, i + 1));
		sprintf(objpath, "%s/%s", path, lines[i]);
		printf("%s lines[i]\n", lines[i]);
		printf("%d isFile\n", isFile(objpath));
		if(isFile(objpath) == 1)
		{
			json_finserter(path);
			system("echo , >> filesystem.json");
		}
		else if (isFile(objpath) == 0)
		{
			strcpy(directories[n], lines[i]);
			n++;			
		}
		else
		{
			break;
		}
	}
	
	int j;
	
	for(j = 0; j < n; j = j+1)
	{
		char new_path[512];
		char new_tmp_file_path[512];
		sprintf(new_path, "%s/%s", path, directories[j]);
		sprintf(new_tmp_file_path, "%s_%s", path, directories[j]);
		json_dinserter((new_path), new_tmp_file_path);
	}
	system("echo ]} >> filesystem.json");
	system(file_paths);

}

//main
int main()
{
	//start and end of object before and after inserting initial dir (filesystem) 
	system("echo { > filesystem.json");
	json_dinserter("filesystem", "filesystem");
	system("echo } >> filesystem.json");

	return 0;
}
